CREATE TABLE [DUKE].[Customers_History](
	[History_ID] [int] IDENTITY(1,1) NOT NULL,
	[EditDate] [datetime] NOT NULL,
	[EditUser] [varchar](75) NOT NULL,
	[ChangeAction] [char](1) NOT NULL,
	[Customer_ID] [int] NOT NULL,
	[Pool] [varchar](25) NOT NULL,
	[Status] [varchar](25) NOT NULL,
	[OpsStatus] [varchar](25) NULL,
	[BillingStatus] [varchar](25) NULL,
	[TaxCode] [bit] NULL,
	[TaxPercent] [float] NULL,
	[CustomerNumber] [varchar](25) NOT NULL,
	[AccountNumber] [varchar](8) NOT NULL,
	[TenantNumber] [varchar](2) NOT NULL,
	[Safari_ID] [varchar](25) NULL,
	[BillMethod] [varchar](10) NOT NULL,
	[MeterNumber] [nvarchar](25) NOT NULL,
	[UtilityAccountID] [nvarchar](25) NOT NULL,
	[CorporateAffiliation] [nvarchar](75) NOT NULL,
	[TigerCustomerName] [nvarchar](75) NOT NULL,
	[CompanyName] [nvarchar](75) NOT NULL,
	[StartDate] [date] NULL,
	[EndDate] [date] NULL,
	[LastBillPeriod] [date] NULL,
	[LastBillStartDate] [date] NULL,
	[LastBillEndDate] [date] NULL,
	[ServiceAddress1] [varchar](30) NULL,
	[ServiceAddress2] [varchar](30) NULL,
	[ServiceCity] [varchar](30) NULL,
	[ServiceState] [char](2) NULL,
	[ServicePostalCode] [varchar](10) NULL,
	[Email] [varchar](75) NULL,
	[BusinessPhone] [varchar](11) NULL,
	[Comments] [varchar](255) NULL,
	[CreatedAt] [datetime] NOT NULL,
	[UpdatedAt] [datetime] NULL,
 CONSTRAINT [PK_Customers_History] PRIMARY KEY CLUSTERED 
(
	[History_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]