CREATE TABLE [DUKE].[Customers_History] (
    [History_ID]           INT           IDENTITY (1, 1) NOT NULL,
    [EditDate]             DATETIME      NOT NULL,
    [EditUser]             VARCHAR (75)  NOT NULL,
    [ChangeAction]         CHAR (1)      NOT NULL,
    [Customer_ID]          INT           NOT NULL,
    [Pool]                 VARCHAR (25)  NOT NULL,
    [Status]               VARCHAR (25)  NOT NULL,
    [OpsStatus]            VARCHAR (25)  NULL,
    [BillingStatus]        VARCHAR (25)  NULL,
    [TaxCode]              BIT           NULL,
    [TaxPercent]           FLOAT (53)    NULL,
    [CustomerNumber]       VARCHAR (25)  NOT NULL,
    [AccountNumber]        VARCHAR (8)   NOT NULL,
    [TenantNumber]         VARCHAR (2)   NOT NULL,
    [Safari_ID]            VARCHAR (25)  NULL,
    [BillMethod]           VARCHAR (10)  NOT NULL,
    [MeterNumber]          NVARCHAR (25) NOT NULL,
    [UtilityAccountID]     NVARCHAR (25) NOT NULL,
    [CorporateAffiliation] NVARCHAR (75) NOT NULL,
    [TigerCustomerName]    NVARCHAR (75) NOT NULL,
    [CompanyName]          NVARCHAR (75) NOT NULL,
    [StartDate]            DATE          NULL,
    [EndDate]              DATE          NULL,
    [LastBillPeriod]       DATE          NULL,
    [LastBillStartDate]    DATE          NULL,
    [LastBillEndDate]      DATE          NULL,
    [ServiceAddress]       VARCHAR (100) NULL,
    [ServiceCity]          VARCHAR (50)  NULL,
    [ServiceState]         CHAR (2)      NULL,
    [ServicePostalCode]    VARCHAR (10)  NULL,
    [Email]                VARCHAR (75)  NULL,
    [BusinessPhone]        VARCHAR (11)  NULL,
    [Comments]             VARCHAR (255) NULL,
    [CreatedAt]            DATETIME      NOT NULL,
    [UpdatedAt]            DATETIME      NULL,
    CONSTRAINT [PK_Customers_History] PRIMARY KEY CLUSTERED ([History_ID] ASC)
);

