CREATE TABLE [Duke].[DailyUsageData]
(
	[UsageId] INT NOT NULL PRIMARY KEY, 
    [Customer_ID] INT NOT NULL, 
    [AccountNumber] VARCHAR(8) NOT NULL, 
	MeterNumber varchar(9) NOT NULL,
    [BillingPeriod] DATETIME NOT NULL, 
    [CustomerAddressLine1] VARCHAR(30) NOT NULL,
	MeterReadFromDate varchar(10) NOT NULL,
	MeterReadToDate varchar(10) NOT NULL,
	MeterReadStart varchar(7) NOT NULL,
	MeterReadEnd varchar(7) NOT NULL,
	GasPressureFactor varchar(5) NOT NULL,
	Usage varchar(10) NOT NULL,
	BillType char(3) NOT NULL,
	BudgetBillingIndicator char(1) NULL,
	SupplierRate char(4) NOT NULL,
	TaxName varchar(37) NOT NULL,
	ChargeAmount Varchar(12) NOT NULL,
	TaxAmount Varchar(12) NOT NULL,
	Savings Varchar(12) Null,
	BalanceReturned varchar(12) NULL,
	MoneyCollected varchar(12) NULL,
	ThirtyDayArrears varchar(11) NULL,
	SixtyDayArrears varchar(11) NULL,
	NintyDayArrears varchar(11) NULL,
	RevenuePeriod varchar(10) NOT NULL,
	SupplierBalance varchar(13) NULL,
	ProcessDate varchar(10) NOT NULL
)
